In [3]:
import pandas as pd
import numpy as np


# Load the data
df = pd.read_csv("load+cal(2019-2023)_removedoutliers(II).csv")
df['DateTime'] = pd.to_datetime(df['DateTime'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41111 entries, 0 to 41110
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DateTime          41111 non-null  datetime64[ns]
 1   Load              41111 non-null  float64
 2   day_part_encoded  41111 non-null  int64
 3   is_weekend        41111 non-null  int64
 4   month_sin         41111 non-null  float64
 5   month_cos         41111 non-null  float64
 6   day_of_week_sin   41111 non-null  float64
 7   day_of_week_cos   41111 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 2.5 MB

In [13]:
wet1= pd.read_csv("POWER_Point_Hourly_20190329_20231205_034d87N_048d53E_LST (1).csv")
wet2= pd.read_csv("POWER_Point_Hourly_20190329_20231205_034d87N_048d53E_LST - Copy.csv")

WET1

In [14]:
# Convert YEAR, MO, DY, HR columns into a single DateTime column
wet1["DateTime"] = pd.to_datetime(wet1[['YEAR', 'MO', 'DY', 'HR']].astype(str).agg('-'.join, axis=1), format="%Y-%m-%d-%H")


# Drop the 'YEAR', 'MO', 'DY', 'HR' columns
wet1 = wet1.drop(columns=['YEAR', 'MO', 'DY', 'HR'])

# Move 'DateTime' to the first column
wet1 = wet1[['DateTime'] + [col for col in wet1.columns if col != 'DateTime']]


wet1.head()

             DateTime     PS  WS10M  WD10M  WS50M  WD50M
0 2019-03-29 00:00:00  81.00   3.92  248.5   6.25  249.4
1 2019-03-29 01:00:00  81.00   3.78  248.3   6.10  249.2
2 2019-03-29 02:00:00  81.05   3.60  253.5   6.05  254.2
3 2019-03-29 03:00:00  81.08   3.34  255.1   5.91  255.5
4 2019-03-29 04:00:00  81.10   2.87  253.6   5.42  253.8

wet2

In [15]:
# Convert YEAR, MO, DY, HR columns into a single DateTime column
wet2["DateTime"] = pd.to_datetime(wet2[['YEAR', 'MO', 'DY', 'HR']].astype(str).agg('-'.join, axis=1), format="%Y-%m-%d-%H")


# Drop the 'YEAR', 'MO', 'DY', 'HR' columns
wet2 = wet2.drop(columns=['YEAR', 'MO', 'DY', 'HR'])

# Move 'DateTime' to the first column
wet2 = wet2[['DateTime'] + [col for col in wet2.columns if col != 'DateTime']]


wet2.head()

,DateTime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,CLRSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,TOA_SW_DWN,ALLSKY_SRF_ALB,SZA,ALLSKY_SFC_PAR_TOT,CLRSKY_SFC_PAR_TOT,ALLSKY_SFC_UVA,ALLSKY_SFC_UVB,ALLSKY_SFC_UV_INDEX,T2M,T2MDEW,T2MWET,ALLSKY_SFC_LW_DWN,QV2M,RH2M,PRECTOTCORR
0,2019-03-29 00:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,0.0,0.0,0.0,-0.33,-0.10,-0.21,251.55,4.67,100.0,0.04
1,2019-03-29 01:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,0.0,0.0,0.0,-0.48,-0.34,-0.41,240.98,4.59,100.0,0.05
2,2019-03-29 02:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,0.0,0.0,0.0,-0.73,-0.66,-0.69,241.12,4.47,100.0,0.06
3,2019-03-29 03:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,0.0,0.0,0.0,-1.05,-1.14,-1.10,243.40,4.32,100.0,0.06
4,2019-03-29 04:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,0.0,0.0,0.0,-1.48,-1.47,-1.47,245.65,4.21,100.0,0.06

In [16]:
wet = wet2.merge(wet1, on='DateTime')
#df3=newdf2.drop(columns=['day_of_week', 'month'])
wet.head()

,DateTime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,CLRSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,TOA_SW_DWN,ALLSKY_SRF_ALB,SZA,ALLSKY_SFC_PAR_TOT,CLRSKY_SFC_PAR_TOT,...,T2MWET,ALLSKY_SFC_LW_DWN,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
0,2019-03-29 00:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,...,-0.21,251.55,4.67,100.0,0.04,81.00,3.92,248.5,6.25,249.4
1,2019-03-29 01:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,...,-0.41,240.98,4.59,100.0,0.05,81.00,3.78,248.3,6.10,249.2
2,2019-03-29 02:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,...,-0.69,241.12,4.47,100.0,0.06,81.05,3.60,253.5,6.05,254.2
3,2019-03-29 03:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,...,-1.10,243.40,4.32,100.0,0.06,81.08,3.34,255.1,5.91,255.5
4,2019-03-29 04:00:00,0.0,0.0,0.0,0.0,0.0,-999.0,90.0,0.0,0.0,...,-1.47,245.65,4.21,100.0,0.06,81.10,2.87,253.6,5.42,253.8

In [17]:
alldata = df.merge(wet, on='DateTime')
#df3=newdf2.drop(columns=['day_of_week', 'month'])
alldata.head()

,DateTime,Load,day_part_encoded,is_weekend,month_sin,month_cos,day_of_week_sin,day_of_week_cos,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DNI,...,T2MWET,ALLSKY_SFC_LW_DWN,QV2M,RH2M,PRECTOTCORR,PS,WS10M,WD10M,WS50M,WD50M
0,2019-03-29 01:00:00,305.032220,5,1,1.0,6.123234e-17,-0.433884,-0.900969,0.0,0.0,...,-0.41,240.98,4.59,100.0,0.05,81.00,3.78,248.3,6.10,249.2
1,2019-03-29 02:00:00,272.552310,5,1,1.0,6.123234e-17,-0.433884,-0.900969,0.0,0.0,...,-0.69,241.12,4.47,100.0,0.06,81.05,3.60,253.5,6.05,254.2
2,2019-03-29 03:00:00,258.534027,5,1,1.0,6.123234e-17,-0.433884,-0.900969,0.0,0.0,...,-1.10,243.40,4.32,100.0,0.06,81.08,3.34,255.1,5.91,255.5
3,2019-03-29 04:00:00,250.893882,1,1,1.0,6.123234e-17,-0.433884,-0.900969,0.0,0.0,...,-1.47,245.65,4.21,100.0,0.06,81.10,2.87,253.6,5.42,253.8
4,2019-03-29 05:00:00,248.525866,1,1,1.0,6.123234e-17,-0.433884,-0.900969,0.0,0.0,...,-1.82,248.45,4.12,100.0,0.06,81.10,2.58,247.4,4.99,247.4

In [18]:
alldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41111 entries, 0 to 41110
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DateTime             41111 non-null  datetime64[ns]
 1   Load                 41111 non-null  float64
 2   day_part_encoded     41111 non-null  int64
 3   is_weekend           41111 non-null  int64
 4   month_sin            41111 non-null  float64
 5   month_cos            41111 non-null  float64
 6   day_of_week_sin      41111 non-null  float64
 7   day_of_week_cos      41111 non-null  float64
 8   ALLSKY_SFC_SW_DWN    41111 non-null  float64
 9   ALLSKY_SFC_SW_DNI    41111 non-null  float64
 10  CLRSKY_SFC_SW_DWN    41111 non-null  float64
 11  ALLSKY_SFC_SW_DIFF   41111 non-null  float64
 12  TOA_SW_DWN           41111 non-null  float64
 13  ALLSKY_SRF_ALB       41111 non-null  float64
 14  SZA                  41111 non-null  float64
 15  ALLSKY_SFC_PAR_TOT   41111 non-null  float64
 16  CLRSKY_SFC_PAR_TOT   41111 non-null  float64
 17  ALLSKY_SFC_UVA       41111 non-null  float64
 18  ALLSKY_SFC_UVB       41111 non-null  float64
 19  ALLSKY_SFC_UV_INDEX  41111 non-null  float64
 20  T2M                  41111 non-null  float64
 21  T2MDEW               41111 non-null  float64
 22  T2MWET               41111 non-null  float64
 23  ALLSKY_SFC_LW_DWN    41111 non-null  float64
 24  QV2M                 41111 non-null  float64
 25  RH2M                 41111 non-null  float64
 26  PRECTOTCORR          41111 non-null  float64
 27  PS                   41111 non-null  float64
 28  WS10M                41111 non-null  float64
 29  WD10M                41111 non-null  float64
 30  WS50M                41111 non-null  float64
 31  WD50M                41111 non-null  float64
dtypes: datetime64[ns](1), float64(29), int64(2)
memory usage: 10.0 MB

In [19]:

# Check for missing values in each column
missing_values = alldata.isnull().sum()

# Print the results
missing_values

DateTime               0
Load                   0
day_part_encoded       0
is_weekend             0
month_sin              0
month_cos              0
day_of_week_sin        0
day_of_week_cos        0
ALLSKY_SFC_SW_DWN      0
ALLSKY_SFC_SW_DNI      0
CLRSKY_SFC_SW_DWN      0
ALLSKY_SFC_SW_DIFF     0
TOA_SW_DWN             0
ALLSKY_SRF_ALB         0
SZA                    0
ALLSKY_SFC_PAR_TOT     0
CLRSKY_SFC_PAR_TOT     0
ALLSKY_SFC_UVA         0
ALLSKY_SFC_UVB         0
ALLSKY_SFC_UV_INDEX    0
T2M                    0
T2MDEW                 0
T2MWET                 0
ALLSKY_SFC_LW_DWN      0
QV2M                   0
RH2M                   0
PRECTOTCORR            0
PS                     0
WS10M                  0
WD10M                  0
WS50M                  0
WD50M                  0
dtype: int64

In [20]:

alldata = alldata.reset_index()
alldata.to_csv('load+cal(2019-2023)_removedoutliers(II)+wet.csv', index=False)